
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "${DASHBOARD_PORT}:3000"
    volumes:
      - ${STORAGE_PATH}/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock # For real-time container stats
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=${SERVER_IP},${SERVER_IP}:${DASHBOARD_PORT}
    restart: unless-stopped
