services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./radarr-config:/config
      - /path/to/movies:/data/movies
      - /path/to/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
